### PR TITLE
Fix release build

### PR DESCRIPTION
**Pull request by Dahlgren**

### CODE REVIEW

**Comment by dedmen** [comment]
Uh wat? No. I don't want MD, I want MT

**Comment by dedmen** [comment]
Ah seems lua is compiled wrongly... Confusing why is that not a problem on my local build :D

**Comment by Dahlgren** [comment]
Yeah, it's either this or fixing lua

**Comment by Dahlgren** [comment]
Changed lua_static to use `MT`

**Comment by dedmen** [comment]
Ah I wondered if that is possible to change flags from outside the lib's subdirectory, good to know that that works

**Pull request merged**
